version: '3.8'

services:
  test_app:
    env_file: 
      - .env
    build: .
    container_name: test_app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
  postgres:
    env_file: 
      - .env
    image: postgres:latest
    container_name: test_postgres_db
    restart: always 
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgress_data:/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgress_data:
